<?php
session_start();
if (!isset($_SESSION['employee_id'])) { header('Location: ../index.php'); exit; }
require_once __DIR__ . '/../config/db.php';

$employeeId = (int)$_SESSION['employee_id'];
$employeeStmt = $conn->prepare('SELECT employee_id,full_name,department,designation FROM employees WHERE id=? LIMIT 1');
$employeeStmt->bind_param('i', $employeeId); $employeeStmt->execute();
$employee = $employeeStmt->get_result()->fetch_assoc();
if (!$employee) { session_destroy(); header('Location: ../index.php?error=invalid_session'); exit; }

$records = [];
try {
    $stmt = $conn->prepare('SELECT * FROM employee_kpi_performance WHERE employee_id=? ORDER BY period_year DESC,period_month DESC,id DESC');
    $stmt->bind_param('i', $employeeId); $stmt->execute(); $records = $stmt->get_result()->fetch_all(MYSQLI_ASSOC);
} catch (Throwable $ignored) {}
$latest = $records[0] ?? null;
$percentage = $latest && (float)$latest['target_score'] > 0 ? min(100, round(((float)$latest['achieved_score'] / (float)$latest['target_score']) * 100, 1)) : 0;
$campaignRecords = [];
try {
    $campaignStmt=$conn->prepare('SELECT p.*,c.name campaign_name FROM campaign_performance p JOIN performance_campaigns c ON c.id=p.campaign_id WHERE p.employee_id=? ORDER BY p.period_year DESC,p.period_month DESC,p.id DESC');
    $campaignStmt->bind_param('i',$employeeId);$campaignStmt->execute();$campaignRecords=$campaignStmt->get_result()->fetch_all(MYSQLI_ASSOC);
    foreach($campaignRecords as &$campaignRecord){$scoreStmt=$conn->prepare('SELECT k.kpi_name,k.weight,s.score FROM campaign_performance_scores s JOIN campaign_kpis k ON k.id=s.kpi_id WHERE s.performance_id=? ORDER BY k.display_order,k.id');$scoreStmt->bind_param('i',$campaignRecord['id']);$scoreStmt->execute();$campaignRecord['scores']=$scoreStmt->get_result()->fetch_all(MYSQLI_ASSOC);}unset($campaignRecord);
} catch(Throwable $ignored) {}
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>My Performance - EMS</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" rel="stylesheet">
<style>body{background:#f4f7fb;font-family:Inter,Arial,sans-serif;color:#172033}.top{background:linear-gradient(135deg,#173a70,#2463b5);color:#fff;padding:26px 0}.card{border:0;border-radius:18px;box-shadow:0 8px 24px rgba(27,49,86,.08)}.metric{font-size:30px;font-weight:800}.rating{display:inline-block;font-size:12px;border-radius:99px;padding:7px 11px;background:#e8f1ff;color:#1d4ed8;font-weight:700}.table th{font-size:12px;text-transform:uppercase;color:#58708f;background:#f7f9fc}.progress{height:12px;border-radius:99px}.empty{padding:65px 20px;text-align:center}.empty i{font-size:50px;color:#8aa4c5}</style></head><body>
<header class="top"><div class="container-fluid px-4 d-flex justify-content-between align-items-center"><div><h2 class="mb-1"><i class="fa fa-chart-line me-2"></i>My KPI & Performance</h2><div class="opacity-75"><?=htmlspecialchars($employee['employee_id'].' · '.$employee['full_name'].' · '.$employee['department'])?></div></div><a href="dashboard.php" class="btn btn-light"><i class="fa fa-arrow-left me-1"></i> Back to Dashboard</a></div></header>
<main class="container-fluid p-4">
<?php if($campaignRecords): ?><div class="card overflow-hidden mb-4"><div class="p-4 pb-2"><h4><i class="fa fa-layer-group text-primary me-2"></i>My Campaign Performance</h4><p class="text-muted">Campaign-wise KPI scorecards assigned to your HRMS Employee Code.</p></div><div class="table-responsive"><table class="table table-bordered align-middle mb-0 text-center"><thead><tr><th>Period</th><th>Campaign</th><?php $allKpis=[];foreach($campaignRecords as $cr)foreach($cr['scores'] as $sc)$allKpis[$sc['kpi_name']]=$sc['weight'];foreach($allKpis as $kn=>$kw):?><th><?=htmlspecialchars($kn)?> (<?=$kw?>%)</th><?php endforeach;?><th>Total</th><th>Grade</th></tr></thead><tbody><?php foreach($campaignRecords as $cr):$byName=[];foreach($cr['scores'] as $sc)$byName[$sc['kpi_name']]=$sc['score'];?><tr><td><?=date('M Y',mktime(0,0,0,$cr['period_month'],1))?></td><td><strong><?=htmlspecialchars($cr['campaign_name'])?></strong></td><?php foreach($allKpis as $kn=>$kw):?><td><?=isset($byName[$kn])?htmlspecialchars($byName[$kn]):'—'?></td><?php endforeach;?><td><strong><?=$cr['total_score']?></strong></td><td><span class="rating"><?=htmlspecialchars($cr['grade'])?></span></td></tr><?php endforeach;?></tbody></table></div></div><?php endif; ?>
<?php if($latest): ?><div class="row g-3 mb-4"><div class="col-md-3"><div class="card p-4"><div class="text-muted">Latest KPI</div><div class="fw-bold fs-5 mt-2"><?=htmlspecialchars($latest['kpi_title'])?></div></div></div><div class="col-md-3"><div class="card p-4"><div class="text-muted">KPI Period</div><div class="metric"><?=date('M',mktime(0,0,0,$latest['period_month'],1)).' '.$latest['period_year']?></div></div></div><div class="col-md-3"><div class="card p-4"><div class="text-muted">Score</div><div class="metric"><?=htmlspecialchars($latest['achieved_score'])?> <small class="fs-6 text-muted">/ <?=htmlspecialchars($latest['target_score'])?></small></div></div></div><div class="col-md-3"><div class="card p-4"><div class="text-muted mb-2">Latest Rating</div><span class="rating"><?=htmlspecialchars($latest['performance_rating'])?></span></div></div></div>
<div class="card p-4 mb-4"><div class="d-flex justify-content-between mb-2"><strong>Latest KPI Achievement</strong><strong><?=$percentage?>%</strong></div><div class="progress"><div class="progress-bar bg-success" style="width:<?=$percentage?>%"></div></div><?php if($latest['remarks']): ?><div class="alert alert-light border mt-4 mb-0"><strong>Manager Remarks:</strong><br><?=nl2br(htmlspecialchars($latest['remarks']))?></div><?php endif; ?></div><?php endif; ?>
<div class="card overflow-hidden"><div class="p-4 pb-2"><h4><i class="fa fa-clock-rotate-left text-primary me-2"></i>My Performance Scorecard</h4><p class="text-muted">Only your own KPI and performance records are shown here.</p></div><?php if(!$records): ?><div class="empty"><i class="fa fa-chart-line mb-3"></i><h4>No Performance Record Yet</h4><p class="text-muted mb-0">Your KPI will appear here after management uploads it.</p></div><?php else: ?><div class="table-responsive"><table class="table table-bordered align-middle mb-0 text-center"><thead><tr><th>S. No</th><th>Period</th><th>ID</th><th>Name</th><th>Designation</th><th>Team</th><th>Team Leader</th><th>Login (5%)</th><th>Withdraw (5%)</th><th>AHT (10%)</th><th>Attendance Till Date (15%)</th><th>Adherence Till Date (5%)</th><th>Call Quality Till Date (30%)</th><th>GC's Conversion (10%)</th><th>Complaint Count (10%)</th><th>Quiz (10%)</th><th>Total Score 100%</th><th>Grade</th></tr></thead><tbody><?php foreach($records as $index=>$row): ?><tr><td><?=$index+1?></td><td><?=date('M Y',mktime(0,0,0,$row['period_month'],1))?></td><td><?=htmlspecialchars($employee['employee_id'])?></td><td class="text-nowrap"><?=htmlspecialchars($employee['full_name'])?></td><td><?=htmlspecialchars($row['designation_snapshot'] ?: $employee['designation'])?></td><td><?=htmlspecialchars($row['team_snapshot'] ?: $employee['department'])?></td><td class="text-nowrap"><?=htmlspecialchars($row['team_leader_snapshot'] ?: '—')?></td><td><?=htmlspecialchars($row['login_score'] ?? '—')?></td><td><?=htmlspecialchars($row['withdraw_score'] ?? '—')?></td><td><?=htmlspecialchars($row['aht_score'] ?? '—')?></td><td><?=htmlspecialchars($row['attendance_score'] ?? '—')?></td><td><?=htmlspecialchars($row['adherence_score'] ?? '—')?></td><td><?=htmlspecialchars($row['call_quality_score'] ?? '—')?></td><td><?=htmlspecialchars($row['gc_conversion_score'] ?? '—')?></td><td><?=htmlspecialchars($row['complaint_score'] ?? '—')?></td><td><?=htmlspecialchars($row['quiz_score'] ?? '—')?></td><td><strong><?=htmlspecialchars($row['total_score'] ?? $row['achieved_score'])?></strong></td><td><span class="rating"><?=htmlspecialchars($row['grade'] ?: $row['performance_rating'])?></span></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></div>
</main></body></html>
