<?php
require_once __DIR__ . '/../config/db.php';
require_once __DIR__ . '/admincheck_role.php';
require_once __DIR__ . '/../config/permissions.php';
if (!isSuperAdmin()) { http_response_code(403); exit('Only Super Admin can manage Access Control.'); }

$roles=getAllRoles($conn); $permissions=getAllPermissions($conn); $modules=getAllModules();
$selectedRoleId=(int)($_POST['role_id']??$_GET['role_id']??($roles[1]['id']??0));
$selectedRole=null; foreach($roles as $role)if((int)$role['id']===$selectedRoleId)$selectedRole=$role;
$message='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
    ems_verify_csrf();
    if(!$selectedRole)$error='Please select a valid role.';
    elseif($selectedRole['role_name']==='Super Admin')$error='Super Admin always has full access and cannot be restricted.';
    else{
        $submitted=$_POST['access']??[];$clean=[];$validModules=array_keys($modules);$validPermissions=array_column($permissions,'permission_slug');
        foreach($submitted as $module=>$items){if(!in_array($module,$validModules,true)||!is_array($items))continue;$clean[$module]=array_values(array_intersect(array_keys($items),$validPermissions));}
        if(saveRolePermissions($conn,$selectedRoleId,$clean))$message='Access permissions saved successfully for '.$selectedRole['role_name'].'.';else$error='Permissions could not be saved.';
    }
}
$current=$selectedRole?getRolePermissions($conn,$selectedRoleId):[];
function checkedAccess(array $current,string $module,string $permission):string{return in_array($permission,$current[$module]??[],true)?'checked':'';}
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Access Control - EMS</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" rel="stylesheet"><link href="admin_panel.css" rel="stylesheet"><style>.access-card{background:#fff;border:1px solid #e2e8f0;border-radius:16px;box-shadow:0 1px 3px #0001}.permission-grid{display:grid;grid-template-columns:repeat(6,minmax(90px,1fr));gap:10px}.permission-box{border:1px solid #e2e8f0;border-radius:10px;padding:10px;text-align:center}.module-row{border-bottom:1px solid #e2e8f0;padding:18px 0}.module-row:last-child{border:0}.dark-mode .access-card,.dark-mode .permission-box{background:#1e293b;color:#e2e8f0;border-color:#334155}@media(max-width:900px){.permission-grid{grid-template-columns:repeat(2,1fr)}}</style></head><body>
<div class="sidebar-backdrop" id="sidebarBackdrop"></div><aside class="sidebar" id="sidebar"><div class="sidebar-brand"><div class="brand-icon"><i class="fa fa-building"></i></div><div class="brand-text">EMS<small>Employee Management</small></div></div><div class="sidebar-user"><div class="user-avatar"><?=htmlspecialchars(strtoupper(substr($admin_name,0,1)))?></div><div class="user-info"><div class="user-name"><?=htmlspecialchars($admin_name)?></div><div class="user-role"><?=htmlspecialchars($admin_role)?></div></div></div><nav class="sidebar-nav">
<div class="sidebar-section-title">Main</div><div class="sidebar-section-group"><a href="dashboard.php" class="sidebar-link"><i class="fa fa-gauge"></i> Dashboard</a><a href="employee.php" class="sidebar-link"><i class="fa fa-users"></i> Employees</a><a href="add_employee.php" class="sidebar-link"><i class="fa fa-user-plus"></i> Add Employee</a><a href="employee_rights_management.php" class="sidebar-link"><i class="fa fa-user-shield"></i> Employee Rights</a><a href="requisitions.php" class="sidebar-link"><i class="fa fa-file-circle-plus"></i> Requisitions</a><a href="leave_requests.php" class="sidebar-link"><i class="fa fa-calendar-check"></i> Leave Requests</a><a href="supervisor_adjustments.php" class="sidebar-link"><i class="fa fa-user-tie"></i> Supervisor Adjustments</a><a href="admin_adjustments.php" class="sidebar-link"><i class="fa fa-shield-alt"></i> Admin Adjustments</a><a href="manage_shifts.php" class="sidebar-link"><i class="fa fa-clock-rotate-left"></i> Manage Shifts</a><a href="attendance_report.php" class="sidebar-link"><i class="fa fa-clock"></i> Attendance</a><a href="reports.php" class="sidebar-link"><i class="fa fa-chart-column"></i> Reports</a></div>
<div class="sidebar-section-title">Payroll</div><div class="sidebar-section-group"><a href="payroll_dashboard.php" class="sidebar-link"><i class="fa fa-money-bill-wave"></i> Payroll Dashboard</a><a href="generate_payroll.php" class="sidebar-link"><i class="fa fa-file-invoice-dollar"></i> Generate Payroll</a><a href="payroll_history.php" class="sidebar-link"><i class="fa fa-clock-rotate-left"></i> Payroll History</a><a href="salary_components.php" class="sidebar-link"><i class="fa fa-wallet"></i> Salary Components</a><a href="salary_slips.php" class="sidebar-link"><i class="fa fa-file-pdf"></i> Salary Slips</a><a href="payroll_reports.php" class="sidebar-link"><i class="fa fa-chart-line"></i> Payroll Reports</a><a href="salary_structure.php" class="sidebar-link"><i class="fa fa-money-bill-wave"></i> Salary Structure</a><a href="monthly_payroll.php" class="sidebar-link"><i class="fa fa-calendar"></i> Monthly Payroll</a></div>
<div class="sidebar-section-title">System</div><div class="sidebar-section-group"><a href="add_notice.php" class="sidebar-link"><i class="fa fa-bullhorn"></i> Notices</a><a href="add_holiday.php" class="sidebar-link"><i class="fa fa-plane"></i> Holidays</a><a href="send_email.php" class="sidebar-link"><i class="fa fa-envelope"></i> Send Email</a><a href="security_audit.php" class="sidebar-link"><i class="fa fa-shield-halved"></i> Security Audit</a><a href="access_control.php" class="sidebar-link active"><i class="fa fa-sliders"></i> Access Control</a><a href="change_password.php" class="sidebar-link"><i class="fa fa-key"></i> Change Password</a><a href="logout.php" class="sidebar-link"><i class="fa fa-right-from-bracket"></i> Logout</a></div></nav></aside>
<div class="main-content" id="mainContent"><header class="header"><div class="header-left"><button class="sidebar-toggle" id="sidebarToggle"><i class="fa fa-bars"></i></button><h4>Access Control <span>/ Roles & Permissions</span></h4></div><div class="header-right"><?php $darkModeInTopbar=true;include('../dark_mode.php');?><a href="logout.php" class="btn btn-danger btn-sm rounded-pill">Logout</a></div></header><main class="page-content">
<?php if($message):?><div class="alert alert-success"><?=htmlspecialchars($message)?></div><?php endif;?><?php if($error):?><div class="alert alert-danger"><?=htmlspecialchars($error)?></div><?php endif;?>
<div class="d-flex justify-content-between align-items-center mb-4"><div><h3 class="mb-1">Role Access Control</h3><p class="text-muted mb-0">Select a role and choose exactly what it can access.</p></div><span class="badge bg-danger-subtle text-danger px-3 py-2"><i class="fa fa-crown"></i> Super Admin Only</span></div>
<div class="access-card p-4 mb-4"><label class="form-label fw-bold">Select Role</label><select class="form-select form-select-lg" onchange="location.href='access_control.php?role_id='+this.value"><?php foreach($roles as $role):?><option value="<?=$role['id']?>" <?=(int)$role['id']===$selectedRoleId?'selected':''?>><?=htmlspecialchars($role['role_name'])?><?=htmlspecialchars($role['role_name']==='Super Admin'?' — Full Access (Locked)':'')?></option><?php endforeach;?></select></div>
<?php if($selectedRole):?><form method="post" class="access-card p-4"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars(ems_csrf_token())?>"><input type="hidden" name="role_id" value="<?=$selectedRoleId?>"><div class="d-flex flex-wrap justify-content-between gap-2 align-items-center mb-3"><div><h5 class="mb-1"><?=htmlspecialchars($selectedRole['role_name'])?> Permissions</h5><small class="text-muted">View, Add, Edit, Delete, Approve and Export can be controlled separately.</small></div><?php if($selectedRole['role_name']!=='Super Admin'):?><div class="d-flex gap-2"><button type="button" class="btn btn-outline-primary btn-sm" id="selectAll">Select All</button><button type="button" class="btn btn-outline-secondary btn-sm" id="clearAll">Clear All</button></div><?php endif;?></div>
<?php foreach($modules as $moduleKey=>$moduleName):?><div class="module-row"><div class="row align-items-center g-3"><div class="col-lg-3"><strong><i class="fa fa-folder-open text-primary me-2"></i><?=htmlspecialchars($moduleName)?></strong></div><div class="col-lg-9"><div class="permission-grid"><?php foreach($permissions as $permission):?><?php $slug=$permission['permission_slug'];?><label class="permission-box"><input type="checkbox" class="form-check-input me-1 access-check" name="access[<?=htmlspecialchars($moduleKey)?>][<?=htmlspecialchars($slug)?>]" value="1" <?= $selectedRole['role_name']==='Super Admin'?'checked disabled':checkedAccess($current,$moduleKey,$slug) ?>><span><?=htmlspecialchars($permission['permission_name'])?></span></label><?php endforeach;?></div></div></div></div><?php endforeach;?>
<?php if($selectedRole['role_name']!=='Super Admin'):?><div class="d-flex justify-content-end pt-4"><button class="btn btn-primary btn-lg px-5"><i class="fa fa-save me-2"></i>Save Access</button></div><?php else:?><div class="alert alert-info mt-4 mb-0"><i class="fa fa-lock me-2"></i>Super Admin automatically has every permission.</div><?php endif;?></form><?php endif;?></main></div>
<script>const sidebar=document.getElementById('sidebar'),backdrop=document.getElementById('sidebarBackdrop');document.getElementById('sidebarToggle').onclick=()=>{sidebar.classList.toggle('open');backdrop.classList.toggle('show')};document.getElementById('selectAll')?.addEventListener('click',()=>document.querySelectorAll('.access-check').forEach(x=>x.checked=true));document.getElementById('clearAll')?.addEventListener('click',()=>document.querySelectorAll('.access-check').forEach(x=>x.checked=false));</script></body></html>
